// version 2 of rock paper scissors generated by AI tools
// improved readability, replaced redundant logic
// uses array for computer choices instead of multiple if statements
// utilizes const and let for better variable scoping


const prompt = require('prompt-sync')();

let playerScore = 0;
let computerScore = 0;

function getComputerChoice() {
    const choices = ['rock', 'paper', 'scissors'];
    const computer = choices[Math.floor(Math.random() * 3)];
    console.log(`CPU says: My choice is ${computer}!`);
    return computer;
}

function getPlayerChoice() {
    while (true) {
        let player = prompt('Please enter either rock, paper, or scissors: ').toLowerCase();
        if (['rock', 'paper', 'scissors'].includes(player)) {
            console.log("Valid input!"); 
            return player;
        }
        console.log('Invalid input. Please enter either rock, paper, or scissors.');
    }
}

function playRound(computer, player) {
    if (computer === player) {
        console.log("Tie! Please play again!");
        return;
    }

    const winConditions = {
        rock: 'scissors',
        paper: 'rock',
        scissors: 'paper'
    };

    if (winConditions[player] === computer) {
        playerScore++;
        console.log(`Player wins! ${player} beats ${computer}!`);
    } else {
        computerScore++;
        console.log(`CPU wins! ${computer} beats ${player}!`);
    }
}

// Run the game
const computerChoice = getComputerChoice();
const playerChoice = getPlayerChoice();
playRound(computerChoice, playerChoice);
